name: Documentation
on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install python dependencies
        run: pip install ase pymatgen
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - name: Instantiate and build packages
        run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()
            Pkg.precompile()
            Pkg.build("DFTK")
          '
      - name: Run doctests
        run: |
          julia --project=docs -e '
            using Documenter: DocMeta, doctest
            using DFTK
            DocMeta.setdocmeta!(DFTK, :DocTestSetup, :(using DFTK); recursive=true)
            doctest(DFTK)'
      - name: Generate docs
        run: julia --project=docs docs/make.jl
        timeout-minutes: 30
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
